name: Deploy to Render

on:
  push:
    branches:
      - main  # Change to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Login to Render
      run: |
        echo "${{ secrets.RENDER_EMAIL }}" > ~/.render.email
        echo "${{ secrets.RENDER_PASSWORD }}" > ~/.render.password
        render login --email $(cat ~/.render.email) --password $(cat ~/.render.password)

    - name: Build and Deploy
      run: |
        render up
